apiVersion: v1
kind: Secret
metadata:
  name:  {{ template "fullname" . }}
data:
  config.json: c3RvcmFnZSAiczMiIHsKICBhY2Nlc3Nfa2V5ID0gInh4eCIKICBzZWNyZXRfa2V5ID0gInh4eCIKICBidWNrZXQgICAgID0gInZhdWx0LWJ1Y2tldCIKfQoKbGlzdGVuZXIgInRjcCIgewogIGFkZHJlc3MgICAgID0gIjAuMC4wLjA6ODIwMCIKICB0bHNfZGlzYWJsZSA9IDEKfQ==  
type: Opaque